### ISSUE TITLE
yarn not starting

### ISSUE THREAD

**Issue by arinzea** [Stavrospanakakis/pneumonia-diagnosis-app#1]
When I run yarn start from the web directory, I get the following error

yarn run v1.22.4
$ react-scripts start
/bin/sh: react-scripts: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Stavrospanakakis** [comment]
Thank you for notice! I updated the README. Try to run:
```
# Go to the web folder
$ cd pneumonia-diagnosis-app/web

# Install dependancies
$ yarn global add react-scripts
$ yarn 

# Run server
$ yarn start
```

If it won't work please let me know.

**Comment by arinzea** [comment]
Hi, yes i saw the update.

I now have a new error
from the web folder I ran yarn and yarn start

$yarn
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.59s.

$ yarn start
yarn run v1.22.4
$ react-scripts start
Attempting to bind to HOST environment variable: x86_64-apple-darwin13.4.0
If this was unintentional, check that you haven't mistakenly set it in your shell.
Learn more here: https://bit.ly/CRA-advanced-config

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND x86_64-apple-darwin13.4.0
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
Emitted 'error' event on Server instance at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1495:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:17) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'x86_64-apple-darwin13.4.0'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Stavrospanakakis** [comment]
It is the first time I see this error. It works in my device. If you haven't fixed the problem try to downgrade react-scripts to 2.1.8. Change it on the package.json and run:
```
# Go to the web folder
$ cd pneumonia-diagnosis-app/web

# Install dependancies
$ yarn global add react-scripts@2.1.8
$ yarn 

# Run server
$ yarn start
```
If it won't work please let me know.

**Comment by arinzea** [comment]
I managed to get it working on Ubuntu 20 via virtualbox however I am not getting any prediction results from the sample test images i downloaded from Kaggle. It uploads ok but when i click on predict nothing happens.

I have installed the dependencies and have wsgi.py running in background. Could it be because the frontend and backend are running at different port numbers? Can you upload a sample image you used also.

yarn frontend
-------------------------------
Compiled successfully!

You can now view pneumonia-diagnosis-app_web in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://10.0.2.15:3000

Note that the development build is not optimized.
To create a production build, use yarn build.

-----------------------------------------------------

wsgi backend

 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
127.0.0.1 - - [26/Jul/2020 18:33:50] "GET / HTTP/1.1" 404 -

**Comment by Stavrospanakakis** [comment]
Logs seem fine. I think that the CORS policy blocks the requests at localhost. If you want to solve this problem, I suggest you to enable a CORS unblock chrome extension. I suggest the one below:
https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino
